### ISSUE TITLE
Need attention

### ISSUE THREAD

**Issue by ABHAY0O7** [castor-software/depclean#102]
Hello @tdurieux 
Sorry to bother you with this new issue, but it has been a long time since you have replied to any of my updates.
Since the program is heading towards the end, I just wanna know that are you still tracking me? 
If yes, then please let me know in this thread. An emoji/reaction will also be sufficient. 😃 

Best
Abhay

**Comment by tdurieux** [comment]
Sorry I had a busy week, i will follow your progress with more attention :)
