### ISSUE TITLE
[FEATURE] handle WAR file and EAR file

### ISSUE THREAD

**Issue by chingchichuang** [castor-software/depclean#107]
Hi,

I would like to ask if DepClean has plan to implement how to handle WAR file and EAR file?
An enterprise archive (EAR) is a wrapper for a Java EE application, which consists of web archive (WAR) and Java archive (JAR) files. 
Thank you!

Best regards,
Ching-Chi

**Comment by cesarsotovalero** [comment]
Hi @chingchichuang, thanks for reaching out.

I've implemented a way for DepClean to decompress and analyze the bytecode in `EAR` and `WAR` files, [see here](https://github.com/castor-software/depclean/commit/12e76e6bf689062f8bbdef00370fb96c8cdc0803). So it should be able to report dependency usages in those files.

Please clone and install from source, try it in your codebase and let me know if it works for you.

**Question:** Do you know about any open-source Maven project that uses a `EAR` or `WAR` dependency to test it?

**Comment by chingchichuang** [comment]
Hi @cesarsotovalero, thank you for the help^______^

I am testing this new feature and find out that [this function](https://github.com/chingchichuang/depclean/blob/master/depclean-core/src/main/java/se/kth/depclean/core/analysis/DefaultProjectDependencyAnalyzer.java#L184) needs to update too.
It seems that project.getArtifacts() does not return dependencies of WAR file.
[This article](https://coderedirect.com/questions/561604/get-dependencies-of-war-artifact-using-maven-2-api) may be a solution.

For the question about EAR and WAR file, I can't find other open-source Maven project that uses EAR or WAR. The Maven project I use is a proprietary project in my internship company. I have checked with my supervisors and they also don't know about this. If I have more information about this, I will let you know! Thank you!!

**Comment by cesarsotovalero** [comment]
Hi @chingchichuang, 

Thanks for pointing at this. 

Would you like to contribute by making a pull request with the working changes as in the`ShareableJarsInWarsExtractor`?

Otherwise, I will try to implement this solution.

**Comment by chingchichuang** [comment]
Hi @cesarsotovalero,

Sure, I am glad to implement this solution. 
I will send a pull request in this week.
Thank you for giving me this opportunity^^

**Comment by chingchichuang** [comment]
Hi @cesarsotovalero,

I follow the probable solution mentioned previously, but it does not detect dependencies inside the war file.
So, I try another implementation like below. I add another if condition in [this method](https://github.com/castor-software/depclean/blob/master/depclean-core/src/main/java/se/kth/depclean/core/analysis/DefaultProjectDependencyAnalyzer.java#L206).

Since WAR files's dependencies are all included under the folder WEB-INF/lib/, I try to decompress WAR file and use classAnalyzer to analyze individual jar file (WEB-INF/lib/*.jar). This step works fine.

However, after getting classes by classAnalyzer, I need to put classes and artifact into artifactClassMap.
My current problem is that I don't know how to create an artifact data structure for jar file (WEB-INF/lib/*.jar).
I try to create an artifact by using DefaultArtifact, but I get runtime error NullPointerException.
DefaultArtifact needs 7 arguements: groupId, artifactId, version, scope, type, classifier, artifactHandler.
I can parse artifactid and version for each jar file, but I don't know how to give classifier and artifactHanlder parameters. Also, I don't know where to get groupId for jar file (WEB-INF/lib/*.jar). 

Currently, I use a workaround. I go to the repository of each WAR file and manually copy their dependencies (in pom.xml) to the pom.xml analyzed by DepClean.

```java
} else if (file != null && file.getName().endsWith(".war")) {
    URL url = file.toURI().toURL();
    acceptWar(url, artifactClassMap);
}
```

```java
private void acceptWar(URL url, Map<Artifact, Set<String>> artifactClassMap) throws IOException, URISyntaxException {
    File file = new File(new URI(url.toString()));
    decompressDependencyFiles(file.getAbsolutePath());
    try (ZipFile zip = new ZipFile(file)) {
        Enumeration<? extends ZipEntry> zipFileEntries = zip.entries();
        while (zipFileEntries.hasMoreElements()) {
            ZipEntry entry = zipFileEntries.nextElement();
            String currentEntry = entry.getName();
            if (currentEntry.matches("^WEB-INF/lib/.*-.*\\.jar$")) {
                String name = currentEntry.substring(currentEntry.lastIndexOf("/") + 1);
                String artifactId = name.substring(0, name.lastIndexOf("-"));
                String version = name.substring(name.lastIndexOf("-") + 1, name.lastIndexOf("."));
                String jarPath = url.toString().substring(0, url.toString().length() - 4) + "/WEB-INF/lib/" + name;
                Set<String> classes = classAnalyzer.analyze(new URL(jarPath));
                Artifact artifact = new DefaultArtifact(null, artifactId, version, "runtime", "jar", null, null);
                artifactClassMap.put(artifact, classes);
            }
        }
    }
}
```

**Comment by cesarsotovalero** [comment]
Hi @chingchichuang,
Please use the latest version of DepClean and confirm if this issue has been fixed or not.
Thanks!

**Comment by chingchichuang** [comment]
Hi @cesarsotovalero,
Thank you! Just see the message today. I will update it this week.
Sorry for not updating for a long time^^
