### ISSUE TITLE
[FEATURE] Differentiating direct transitive and inherited transitive dependencies

### ISSUE THREAD

**Issue by afillatre** [castor-software/depclean#124]
**Is your feature request related to a problem? Please describe.**
Since we can't do much to debloat inherited transitive dependencies, it could be nice to separate them from the ones that come from direct dependencies, for clarity sake.

**Describe the solution you'd like**
Separate both kinds of transitive dependencies in the final report

**Comment by cesarsotovalero** [comment]
Hi @afillatre, 

Inherited dependencies are all the dependencies that come from the parent project.
I agree with you that it makes sense to separate "inherited direct" and "inherited transitive" dependencies.

So, I think the change that you're proposing look as follows?

```diff
USED DIRECT DEPENDENCIES [0]: 
USED TRANSITIVE DEPENDENCIES [0]:
- USED INHERITED DEPENDENCIES [0]:
+ USED INHERITED DIRECT DEPENDENCIES [0]: 
+ USED INHERITED TRANSITIVE DEPENDENCIES [0]: 
POTENTIALLY UNUSED DIRECT DEPENDENCIES [0]: 
POTENTIALLY UNUSED TRANSITIVE DEPENDENCIES [0]: 
- POTENTIALLY UNUSED INHERITED DEPENDENCIES [0]:
+ POTENTIALLY UNUSED INHERITED DIRECT DEPENDENCIES [0]: 
+ POTENTIALLY UNUSED INHERITED TRANSITIVE DEPENDENCIES [0]: 
}

Is this correct?
