### ISSUE TITLE
[BUG] DepClean failing for a Java 11 project

### ISSUE THREAD

**Issue by t1** [castor-software/depclean#127]
**Describe the bug**
I have a project with source and target set to 11. When I run `mvn se.kth.castor:depclean-maven-plugin:2.0.1:depclean`, it fails with:

`[ERROR] Failed to execute goal se.kth.castor:depclean-maven-plugin:2.0.1:depclean (default-cli) on project wunderbar.lib: Execution default-cli of goal se.kth.castor:depclean-maven-plugin:2.0.1:depclean failed: Unsupported class file major version 60`

**To Reproduce**
1. checkout some jdk 11 project, e.g. https://github.com/t1/wunderbar
2. use maven 3.8.5 and jdk 11.0.14-librca
3. `mvn se.kth.castor:depclean-maven-plugin:2.0.1:depclean`

**Expected behavior**
it should just work

**Screenshots**
n/a

**Additional context**
n/a

**Comment by cesarsotovalero** [comment]
Hi @t1, 

Thanks for opening this issue.
Version 2.0.2 of DepClean has been released and it should work well with projects that use JDK <= 17. 
I've successfuly executed DepClean in https://github.com/t1/wunderbar.

Please run the following commands and tell me if it works for you as well:

```bash
cd TO_YOUR_MAVEN_MODULE
mvn clean compile
mvn compiler:testCompile
mvn se.kth.castor:depclean-maven-plugin:2.0.2:depclean
```

**Comment by t1** [comment]
Yes, this works. Thanks a lot!
