### ISSUE TITLE
[BUG] Record requires ASM8

### ISSUE THREAD

**Issue by TidensBarn** [castor-software/depclean#129]
Working with Java 17, Maven 3.8.4 and using Records in my code. Depclean doesn't seem to like that:

`[ERROR] Execution default of goal se.kth.castor:depclean-maven-plugin:2.0.2:depclean failed: Record requires ASM8`

**Comment by cesarsotovalero** [comment]
Hi @TidensBarn, 

Thanks for reporting this issue. 
It should have been fixed with https://github.com/castor-software/depclean/commit/bb207e30f26428b4bdfb2cbb3c6b01517d945ee2

Please let me know if it works now on your side.

**Comment by TidensBarn** [comment]
Nice! I tried it and the the build does work now.
Thank you!
