### ISSUE TITLE
No debloated-pom.xml 

### ISSUE THREAD

**Issue by harpreet86** [castor-software/depclean#131]
I have used <createPomDebloated> configuration as true as shown in screenshot but it is not generating any debloated-pom.xml
<img width="416" alt="image" src="https://user-images.githubusercontent.com/4299180/177767348-c940e29b-c577-45ab-b01f-46bb705f2e65.png">

**Comment by cesarsotovalero** [comment]
Hi @harpreet86, 
Thanks for reporting this issue.
The configuration of DepClean in your `pom.xml` is correct. 

Could you please give a pointer to the repository you're using?
This way I can have a closer look and debug.

Thanks.

**Comment by cesarsotovalero** [comment]
I'm closing this issue due to a lack of engagement.
