### ISSUE TITLE
Maven plugin issue

### ISSUE THREAD

**Issue by rohanmukesh** [castor-software/depclean#3]
We are getting this issue:

[ERROR] Plugin se.kth.castor:depclean-maven-plugin:1.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for se.kth.castor:depclean-maven-plugin:jar:1.0.0: Could not find artifact se.kth.castor:depclean-parent-pom:pom:1.0.0 in central (https://repo.maven.apache.org/maven2) ->

We have added the plugin and goal under build section of pom.xml as specified in the ReadMe.

**Comment by cesarsotovalero** [comment]
Did you try installing and building from source?
Clone the repo and run `mvn clean install`. After that, add the plugin to the `pom` of your project, as described in the README.

**Comment by cesarsotovalero** [comment]
@rohanmukesh please close this issue if you solved the problem.

**Comment by cesarsotovalero** [comment]
I'm closing this issue due to a lack of engagement.
