### ISSUE TITLE
IllegalArgument Exception

### ISSUE THREAD

**Issue by SagarGupta1** [castor-software/depclean#32]
Hi Team,
When I am running the mvn se.kth.castor:depclean-maven-plugin:1.1.2-SNAPSHOT:depclean -Dcreate.pom.debloated=true -Dcreate.result.json=true I am getting :

Failed to execute goal se.kth.castor:depclean-maven-plugin:1.1.2-SNAPSHOT:depclean (default-cli) on project req-lineitem-srv: Execution default-cli of goal se.kth.castor:depclean-maven-plugin:1.1.2-SNAPSHOT:depclean failed.: IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal se.kth.castor:depclean-maven-plugin:1.1.2-SNAPSHOT:depclean (default-cli) on project req-lineitem-srv: Execution default-cli of goal se.kth.castor:depclean-maven-plugin:1.1.2-SNAPSHOT:depclean failed.

My Configuration are:
[DEBUG] Configuring mojo 'se.kth.castor:depclean-maven-plugin:1.1.2-SNAPSHOT:depclean' with basic configurator -->
[DEBUG]   (f) createPomDebloated = true
[DEBUG]   (f) createResultJson = true
[DEBUG]   (f) failIfUnusedDirect = false
[DEBUG]   (f) failIfUnusedInherited = false
[DEBUG]   (f) failIfUnusedTransitive = false
[DEBUG]   (f) ignoreDependencies = []
[DEBUG]   (f) ignoreScopes = []
[DEBUG]   (f) project = MavenProject: com.sap.requisitioning:req-lineitem-srv:0.0.1 @ C:\Requistion-Workspace\RequisitionLineItem\srv\pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@4cc7d00d
[DEBUG]   (f) skipDepClean = false
[DEBUG] -- end configuration --

Thanks
Sagar Gupta

**Comment by cesarsotovalero** [comment]
Hi @SagarGupta1, 

Can you run DepClean with stacktraces turned on to see which LOC is causing the problem?

Please execute: `mvn se.kth.castor:depclean-maven-plugin:1.1.2-SNAPSHOT:depclean -Dcreate.pom.debloated=true -Dcreate.result.json=true -e`

**Comment by cesarsotovalero** [comment]
Hi @SagarGupta1, I'm closing this issue due to a lack of engagement. Please open another issue if you want to.
