### ISSUE TITLE
Looking for Google Summer of Code (GSoC) students

### ISSUE THREAD

**Issue by cesarsotovalero** [castor-software/depclean#37]
Hi, 

DepClean is part of Google Summer of Code, as a subproject of the [CASTOR Software Research Centre](https://www.castor.kth.se/).

If you'd like to be a DepClean contributor as part of GSoC, drop a comment on this issue.

Best,
César

**Comment by Rakshit11** [comment]
I'm interested in DepClean for contribution with good development skills

**Comment by cesarsotovalero** [comment]
Welcome @Rakshit11! Can you make a PR adding tests, refactoring, or fixing bugs?

**Comment by ChristosToxiadis** [comment]
Hello my name is Chris, and i would like to contribute because i think that this is an interesting Project.

**Comment by yashrajjain726** [comment]
Hi @cesarsotovalero !

I'm Yashraj, a learning enthusiast from Cv Raman Global University, Bhubaneshwar pursuing B.Tech in Computer Science. I am a Competitive Java Programmer and a Web Developer too. I have learned the concepts of Java on OOPs and I also practice Data Structures and Algorithms using Java.

I really like this project and would certainly devote my time to contribute to it. I have also contributed to open source communities before in 2020. I would like you to please guide me through the topics that I could learn, by which I can contribute to your project and get started on it. 

Sir, you can too look at my coding profiles mentioned below : 
[Codechef](https://www.codechef.com/users/yashrajjain6)
[Leetcode](https://leetcode.com/yashrajjain726)
[GeeksForGeeks](https://auth.geeksforgeeks.org/user/yashrajjain726/practice/)

**Comment by Rakshit11** [comment]
> Welcome, @Rakshit11! Can you make a PR adding tests, refactoring, or fixing bugs?

On it

**Comment by yashrajjain726** [comment]
Hey @cesarsotovalero ! I saw the documentation and I got to know that the project is made using Maven, so I am learning that part of Java. So, can you please tell me that, what are other topics that I need to learn to contribute to this project? I will learn all those topics asap, and start to contribute to this great project.

**Comment by cesarsotovalero** [comment]
A good starting point to learn is the companion research paper [A Comprehensive Study of Bloated Dependencies in the Maven Ecosystem](https://arxiv.org/abs/2001.07808).

**Comment by ABHAY0O7** [comment]
Hey @cesarsotovalero! I am Abhay a first-year student pursuing B.tech with IT as a major part of my study at the Indian Institute of Information Technology, Allahabad. I will like to work on this project this summer and after that too. I have an overview of this  project and also want to discuss about the GSoC project and the issues that are mentioned [here](https://docs.google.com/document/d/1zCRSd0M4rVbyyDqUPDTTu0FihMuyotTZCTaw-48ort0/edit)

Also in Project ideas, there is a feature request of implementing the Gradle plugin for depclean, but that branch is currently unstable and also not get merged into master. So I wanna ask that can I work on that branch too?

Thank you
Abhay

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, thanks for reaching out. I've noticed that you have already contributed to this repo: that's great! We'll select one student to work in DepClean as part of the GSoC. The most important quality that we're looking for is the ability to make high-quality contributions to our codebase. Therefore, having accepted PRs is a great indicator for us when choosing candidates.

Implementing the Gradle plugin for DepClean is a milestone. If someone is able to implement it, then good chances are that he/she will be selected for the GSoC. You can open an issue if you want to clarify the technical details.

**Comment by KishkinJ10** [comment]
sir i am a beginner and want to start my open source journey for GSoC 2021 can you suggest me something in which i can contribute?

**Comment by ABHAY0O7** [comment]
Hey! @cesarsotovalero,
I wanted to discuss more about the project specifically the depclean-gradle-plugin. But I am facing some difficulties in using the mailing list provided by the Castor organization. I am not understanding that how can I communicate with you on that mailing list. Can you please help me regarding this issue? 

Thank you

**Comment by cesarsotovalero** [comment]
> I wanted to discuss more about the project specifically the depclean-gradle-plugin. 

Then the way is by opening an issue on this repo.

> But I am facing some difficulties in using the mailing list provided by the Castor organization. I am not understanding that how can I communicate with you on that mailing list. Also, the link of CONTACT MAIL provided castor organization on the GSoC website is not working. So can you please help me regarding this issue?

The mailing list is not for communications regarding technical details. It is intended to be used for general questions with the candidates. For technical questions please open an issue in this repo.

> Can I contact you on this mail `cesarsotovalero@gmail.com`?

No, my personal e-mail is not for this purpose.

> Please help me.

The best you can do as a candidate is to demonstrate your technical and communication skills with pull-requests on this repo. You can start with easy-to-do issues (refactoring, adding tests, etc.). This will make us consider you as a strong candidate, so being more likely to be selected.

**Comment by ABHAY0O7** [comment]
Hello! @cesarsotovalero,
I have successfully shared my draft proposal for this project on GSoC official website.
[Here](https://docs.google.com/document/d/1WG1kZ5bHKFLf2PCKPQdWQn2VSGbvdQBJ6eixddJMmNs/edit) is the link for my draft proposal.
I will love to get your suggestions in the comments so that my proposal can add more value to this project and can become more beneficial for the organization, and me too.
And if you already reviewed it then please tell me that too so that I can finally upload a pdf of my draft proposal.

Thank you
Abhay

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, I've revised your proposal (added comments there).

**General comment:** The current version of your proposal is vague. You need to be more specific. Describe exactly how do you plan to accomplish each of the tasks. The most important is to be focused. For example, in the case of the Gradle plugin, give a pointer to some related documentation on the topic, and make a figure with the architecture that you plan to implement. It is not the number of tasks that matters most for us. What we want to see is a clear description of how are you going to complete some task, to be sure that you have the knowledge and skills to do so.

**Comment by ABHAY0O7** [comment]
Hello @cesarsotovalero,
I understand that what do you want from me.
I added some new plans and approaches for some tasks and also resolved most of your comments.
It is true that currently, I have no idea for the implementation of the Gradle plugin but I am working on it and I need some more time for that. 
And also, since there are only 3 hrs. left for the final submission of the proposal, therefore I want you to take a look over what I proposed in the plan and approach for the multi-module task and the test task. (Also here #68)
I also want to know that if unfortunately I unable to propose a plan for the Gradle plugin then may I drop that task and include the Github bot and depclean page task. (Only if Gradle plugin implementation, isn't a mandatory task).

Waiting for your lightning response...

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, I went over your proposal. The current version looks better, but it still far from being great. The Gradle plugin is a milestone in this project, and we understand that the chosen candidate may need some time to do it, which is fine. 

Since the submission deadline is approaching, I recommend you submit your current version as it is. We have received many applications. However, only a few candidates (notably you!) have shown a serious level of engagement with this project. 

A commission will revise your proposal. They will decide. Stay tuned!
