### ISSUE TITLE
Image URL issue !

### ISSUE THREAD

**Issue by yashrajjain726** [castor-software/depclean#40]
In the  [Depclean Github Deployed Page](https://castor-software.github.io/depclean/) the image URL is expired. Please change the URL, by setting the project locally and changing the link to [this link](https://github.com/castor-software/depclean/blob/master/.img/logo.svg).

Here is the sample screenshot, that I wanted to attach with this issue. So, that the issue can be confirmed.

![Image URL error screenshot](https://user-images.githubusercontent.com/53373012/111195969-d35b2100-85e2-11eb-9188-a670936c45ec.jpg)

**Comment by cesarsotovalero** [comment]
Hi @yashrajjain726, thanks for reporting this issue.
The GitHub page of DepClean is outdated. 
We want to create a new and better one.
I'm opening a new issue (https://github.com/castor-software/depclean/issues/41) for this.

**Comment by cesarsotovalero** [comment]
Moved to https://github.com/castor-software/depclean/issues/41
