### ISSUE TITLE
[BUG] Checkstyle report is generating for sun_shecks instead of google_checks.

### ISSUE THREAD

**Issue by ABHAY0O7** [castor-software/depclean#42]
**Description of the bug**
In the pom.xml file of the maven plugin, it is mentioned that google style is adopted for the checkstyle plugin but after running 
 `mvn checkstyle:checkstyle` the report generated in checkstyle.html is for sun checks.

**To Reproduce**
1. Go to '\depclean\depclean-maven-plugin\target\checkstyle-checker.xml'
2. See line no. 63
3. Run `mvn checkstyle:checkstyle`
4. Go to '\depclean\depclean-maven-plugin\target\site\checkstyle.html'
5. Open this file with your browser and read the first line.

**Expected behavior**
The first line you read above should contain google_checks.xml instead of sun_checks.xml and the whole report should show errors of google_checks instead of sun_checks.

**Screenshots**
![image](https://user-images.githubusercontent.com/75938293/111273693-202e0e80-865a-11eb-98bb-6aa47cbc2410.png)

![image](https://user-images.githubusercontent.com/75938293/111273572-fffe4f80-8659-11eb-9cf3-c8091c956c04.png)

**Additional context**
It might also happen that the report is correct but the comment which is showing that google_checks are adopted is wrong.

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, thanks for the bug report.
The Chekstyle report was fixed in https://github.com/castor-software/depclean/commit/2d5e12996b9cd5e580b8583ee03963e740e3cab6

Can you make a pull on the last version of the project and confirm that it is fixed?

**Comment by yashrajjain726** [comment]
I checked that part, it is fixed.

**Comment by cesarsotovalero** [comment]
Great, thanks @yashrajjain726
