### ISSUE TITLE
DepClean doesn't fully extract JAR content when the extraction of a single file fails

### ISSUE THREAD

**Issue by mtorres10** [castor-software/depclean#47]
**Is your feature request related to a problem? Please describe.**
When analyzing for some dependencies, for example selenium (see https://github.com/castor-software/depclean/issues/46) due an odd jar structure depclean does not fully extract jar contents, so not all classes are analized

**Describe the solution you'd like**
Allow the extraction of files to continue, and print a warning of which file caused an issue.

**Comment by mtorres10** [comment]
PR for this feature request is [here](https://github.com/castor-software/depclean/pull/48#pullrequestreview-614964091)

**Comment by cesarsotovalero** [comment]
Thank @mtorres10. I reviewed your PR. Please remove all the changes that are not related to the fix, as I mentioned in the review. Once you do that, I'll accept your PR.

**Comment by mtorres10** [comment]
@cesarsotovalero  PR has been fixed as requested.
