### ISSUE TITLE
Add scope information to potentially unused dependencies 

### ISSUE THREAD

**Issue by henrikplate** [castor-software/depclean#5]
Great idea, thank you (again).

It would be very helpful to see the scope of unused dependencies, or maybe exclude certain scopes from the analysis. IMO, debloating is particularly useful for those scopes needed at runtime.

**Comment by bbaudry** [comment]
+1 for the exclusion of certain scopes from the analysis

**Comment by cesarsotovalero** [comment]
Thanks, @henrikplate, we have added scope information of each dependency to the report.

We also added a parameter to the plugin that allows excluding dependencies with particular scopes from the Depclean analysis. This way, the users have the option of removing unused dependencies that are only needed at runtime, if they want to.
