### ISSUE TITLE
master version still keeps references to 1.0.0 (and fails)

### ISSUE THREAD

**Issue by jfneis** [castor-software/depclean#6]
When trying to download and build the source code, there is a problem because core version 1.0.0 is broken (can't find parent POM).

Changing the plugin version solved the issue.

Same way, the documentation (README) still refers 1.0.0 version, which results in an error when trying to run the plugin in other projects.

**Comment by cesarsotovalero** [comment]
@jfneis We released a new version [1.1.0](https://github.com/castor-software/depclean/releases/tag/1.1.0) of DepClean. Thanks for noticing the bug in the documentation.
