### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ABHAY0O7** [castor-software/depclean#66]
Hey! @cesarsotovalero,
I am really sorry to open this issue but I am facing some problems in communicating with you, please reply to this issue #37 conversation. I have asked a question there.

Thank you
Abhay

**Comment by cesarsotovalero** [comment]
> I am really sorry to open this issue but I am facing some problems in communicating with you, please reply to this issue #37 conversation. I have asked a question there.

Opening issues actually the best way to communicate and improve the project. Don't hesitate to open issues here. I've answered your question in #37.
