### ISSUE TITLE
Checkstyle report is generating for sun_checks instead of google_checks

### ISSUE THREAD

**Issue by ABHAY0O7** [castor-software/depclean#70]
The problem about the checkstyle that I mention in this issue #42 still exists.
----------------------------------------------------------------------------------------------------------------------------------------------
See report generated:
![image](https://user-images.githubusercontent.com/75938293/113521521-92d63e00-95b7-11eb-885c-a12fbf74c3e7.png)
----------------------------------------------------------------------------------------------------------------------------------------------
In code too:
![Screenshot 2021-04-05 024904](https://user-images.githubusercontent.com/75938293/113521843-b00c0c00-95b9-11eb-87a8-060af0bb3adf.png)
----------------------------------------------------------------------------------------------------------------------------------------------
But this time I also got the cause for it.
In the project's pom file it is clearly mentioned that Google_checks are adopted. 
----------------------------------------------------------------------------------------------------------------------------------------------
See this 
![Screenshot 2021-04-05 024255](https://user-images.githubusercontent.com/75938293/113521686-bc439980-95b8-11eb-8d25-a5ede8087b87.png)
----------------------------------------------------------------------------------------------------------------------------------------------
It is true that in the parent checkstyle module, the configuration is of google checks.
See 
![Screenshot 2021-04-05 030632](https://user-images.githubusercontent.com/75938293/113522153-f3677a00-95bb-11eb-9d48-5afd0e4aaf52.png)
----------------------------------------------------------------------------------------------------------------------------------------------
But the module that is configured in both depclean core and maven plugin is of sun_checks.
See this
![image](https://user-images.githubusercontent.com/75938293/113521750-29572f00-95b9-11eb-9720-b62def11f319.png)
----------------------------------------------------------------------------------------------------------------------------------------------

So it can be fixed either by mentioning that sun_checks are adopted in parent pom file or replace the checkstyle with [this one](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) in both depclean core as well as  in maven plugin.
I can fix this issue but please suggest to me the correct way (mentioned above) of fixing this issue.

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, thanks for reporting this issue.

Checkstyle is part of the DepClean CI pipeline. If you look at the `pom.xml` of the DepClean modules (eg. https://github.com/castor-software/depclean/blob/master/depclean-core/pom.xml#L48), you will notice that the configuration file used is the `checkstyle.xml` located at the root of the repo, which is actually a less strict version of the Google conventions, see https://github.com/castor-software/depclean/blob/master/checkstyle.xml.

If you run `mvn checkstyle:checkstyle` then the default `maven-checkstyle-plugin` is executed, which is configured to use the `sun_checks`. To run the Checkstyle configured for this project (which should trigger no errors), you should run `mvn validate` for if you want to run `check` Checkstyle goal (see https://github.com/castor-software/depclean/blob/master/depclean-core/pom.xml#L52) or `mvn verify` for the `checkstyle` goal that generates the report (see https://github.com/castor-software/depclean/blob/master/depclean-core/pom.xml#L52).

To fix the issue and get the correct report when running `mvn checkstyle:checkstyle`, the  property `<checkstyle.config.location>../checkstyle.xml</checkstyle.config.location>` needs to be added in the `pom.xml` (see https://stackoverflow.com/a/14010915/10480869).

**Comment by cesarsotovalero** [comment]
@ABHAY0O7 Please close this issue IF https://github.com/castor-software/depclean/pull/71 fixed this issue. Thanks.

**Comment by ABHAY0O7** [comment]
Thanks, @cesarsotovalero,
I checked it and the issue is solved.
