### ISSUE TITLE
[BUG] Mapstruct processor dependency is deleted

### ISSUE THREAD

**Issue by afillatre** [castor-software/depclean#76]
**Describe the bug**
After depclean completes, and given mapstruct processor is used, the `mapstruct-processor` direct dependency is not longer present on the debloated `pom.xml`

**To Reproduce**
1. Configure the maven-processor-plugin to use the mapstruct annotation
```
      <plugin>
        <groupId>org.bsc.maven</groupId>
        <artifactId>maven-processor-plugin</artifactId>
        <executions>
          <execution>
            <id>process</id>
            <goals>
              <goal>process</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <processors>
                <processor>org.mapstruct.ap.MappingProcessor</processor>
              </processors>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
2. Add required mapstruct dependencies
```
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct-processor</artifactId>
      <scope>provided</scope>
    </dependency>
```
3. Run depclean with debloated-pom generation

**Expected behavior**
`mapstruct-processor` dependency is conserved

**Additional context**
Mapstruct generates code during the `generated-sources` phase, but do not keep `mapstruct-processor` imports in the generated classes. This may be why it is eventually removed from the debloated-pom.

One could manually list this dependency into the `ignoreDependencies` configuration, but it may be better to consider annotation processor classes to be rightful `provided` dependencies

**Comment by cesarsotovalero** [comment]
Hi @afillatre, thanks for reporting this issue.

Can you please give more details about this proposal:

> ... but it may be better to consider annotation processor classes to be rightful `provided` dependencies

**Comment by afillatre** [comment]
Yes. Given this plugin configuration
```
      <plugin>
        <groupId>org.bsc.maven</groupId>
        <artifactId>maven-processor-plugin</artifactId>
        <executions>
          <execution>
            <id>process</id>
            <goals>
              <goal>process</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <processors>
                <processor>org.mapstruct.ap.MappingProcessor</processor>
              </processors>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

Depclean could consider `org.mapstruct.ap.MappingProcessor` to be rightfully part of the project, and add it to the Dependency Usage Analysis, because it is declared in the pom as a processor

**Comment by cesarsotovalero** [comment]
@afillatre, I understand your proposal. 
It is definitely not difficult to implement some rules that analyze the `xml` pom to consider this and other similar usage cases.

I'll implement the pom rule parser ASAP. 

If you feel comfortable with the task, the debloated-pom is generated here https://github.com/castor-software/depclean/blob/master/depclean-maven-plugin/src/main/java/se/kth/depclean/DepCleanMojo.java#L586-L658.
