### ISSUE TITLE
[BUG] Lombok provided dependency is deleted

### ISSUE THREAD

**Issue by afillatre** [castor-software/depclean#77]
**Describe the bug**
After depclean completes, and given lombok is used, the lombok direct dependency is not longer present on the debloated `pom.xml`

**To Reproduce**
1. Use Lombok (for instance `@Data` annotation) with its dependency
2. Run depclean

**Expected behavior**
Lombok is kept in the debloated pom

**Additional context**
Lombok does bytecode modification, removing all traces of itself while generating plumber code. That is why it is not present in the analyzed bytecode. It is visible in the source code, though.

**Comment by cesarsotovalero** [comment]
Hi @afillatre, we are aware of this case. Lombok manipulates the bytecode at runtime, so there is no way for a tool like DepClean to notice that it is being used. 

One way to mitigate this issue is implementing source code analysis, which still does not guarantee that all the dynamic usages will be caught.

If you want to make sure that lombok is kept in the debloated pom, just configure DepClean with the `ignoreDependencies` parameter.

**Comment by afillatre** [comment]
Yes, I figured I much and used that workaround. I have no other solution ATM, other than doing a quick source code search for well-known libraries that work this way (which implies a tighter coupling to specific libs :/)

**Comment by afillatre** [comment]
BTW, what's the point of cleaning `provided` dependencies ? Those dependency are not included in the packaging (by design), so why bother cleaning them ?
That may actually fix some issues with Lombok, Mapstruct, etc.

**Comment by cesarsotovalero** [comment]
> BTW, what's the point of cleaning `provided` dependencies ? Those dependency are not included in the packaging (by design), so why bother cleaning them ?

We want to make DepClean as configurable as possible. That's why the `ignoreScopes` parameter is provided. The user can choose not to analyze dependencies with specific scopes as desired, e.g. `test` and `provided` scopes.

**Comment by afillatre** [comment]
I see. Maybe `provided` (and even `test`) scope(s) should be excluded by default to avoid those issues ? Anyway, it's good that it is a much configurable :)
