### ISSUE TITLE
Implement web graph tool for dependencies

### ISSUE THREAD

**Issue by cesarsotovalero** [castor-software/depclean#8]
It would be useful to implement a web graph tool for DepClean, in the same spirit of https://github.com/ExpediaGroup/jarviz/tree/master/jarviz-graph.

The web interface must show the dependency analysis results for an uploaded project. The tool will show the results as a DAG with the following information:
- The direct, transitive, and inherited dependencies as nodes
- The status of those dependencies (used or bloated) as colored edges

**Comment by bbaudry** [comment]
The visualization of dependency trees is also related to [Surfacing Hidden Change to Pull Requests](https://developer.squareup.com/blog/surfacing-hidden-change-to-pull-requests/)

**Comment by bbaudry** [comment]
@imjhonny is working on this issue
TODO:
- [ ] one view of the module and only its direct dependencies
  - [ ] with all direct dependencies
  - [ ] with omitted / non omitted deps
  - [ ] with direct used / direct bloated / omitted
- [ ] 'expand' this view with inherited dependencies (with same 3 filters as above)
- [ ] expand more with all transitive dependencies
- [ ] have some charts to give an overview. for example, a pie chart that shows the proportion of direct / inherited / transitive used/bloated

**Comment by cesarsotovalero** [comment]
This issue has moved to the following repo https://github.com/castor-software/depclean-web
