### ISSUE TITLE
Porting Maven tests to Gradle tests

### ISSUE THREAD

**Issue by bbaudry** [castor-software/depclean#91]
This folder includes small Maven projects to be used for testing Depclean with Maven:
https://github.com/castor-software/depclean/tree/master/depclean-maven-plugin/src/test/resources-its/

@ABHAY0O7, can you add build.gradle files for each of these projects, so you can use them to test the Depclean gradle plugin?

**Comment by ABHAY0O7** [comment]
Hi! @bbaudry,
I think you are saying that I have to convert these maven projects into Gradle projects so that I can use them in testing of Gradle plugin?
If Yes, then this single command `gradle init` will do the whole work for me. 
If this approach is not correct, then enlighten me with some correct ways of doing this.

Thank you

**Comment by bbaudry** [comment]
> I think you are saying that I have to convert these maven projects into Gradle projects so that I can use them in testing of Gradle plugin?

You are right @ABHAY0O7, that's exactly the goal

**Comment by ABHAY0O7** [comment]
Hello @bbaudry @tdurieux 
I need some help!
As in the Maven plugin, we copy all the dependencies locally by invoking the maven command 
`mvn dependency:copy-dependencies -DoutputDirectory=$buildDir\dependencies`. See [here](https://github.com/castor-software/depclean/blob/cbfc3954b429a124d92d18f125aac3daaf0b5f68/depclean-maven-plugin/src/main/java/se/kth/depclean/DepCleanMojo.java#L368)
But in a Gradle project to copy dependencies locally, I am unable to find the exact command which can be directly used from the terminal. All I am getting is this configurations that I have to add manually in my buld.gradle file.

    task copyToLib(type: Copy) {
        into "$buildDir/output/lib"
        from configurations.runtime
    }

But I need the corresponding command that I can directly invoke from the terminal.
Can you please tell me the exact command for this?

Thank you
Abhay

**Comment by tdurieux** [comment]
There is probably no command for that. You will need to code it. You can do that by taking the classpath and copying all the dependency in the good folder

**Comment by tdurieux** [comment]
I meant that you can replace this part of the code https://github.com/castor-software/depclean/blob/cbfc3954b429a124d92d18f125aac3daaf0b5f68/depclean-maven-plugin/src/main/java/se/kth/depclean/DepCleanMojo.java#L370 with your own java method that does the same thing.
